# Generated by Django 3.0.5 on 2020-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_label',
            field=models.ManyToManyField(blank=True, to='fundoo.Label'),
        ),
    ]
