# Generated by Django 3.0.5 on 2020-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0002_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
