# Generated by Django 3.0.5 on 2020-04-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0003_registration_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='profile_pic',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
