# Generated by Django 3.0.5 on 2020-04-24 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundoo', '0005_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Label', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
