# Generated by Django 3.0.5 on 2020-04-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0006_auto_20200424_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
